-- MySQL Script generated by MySQL Workbench
-- Sun Sep  7 20:02:49 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema terastore
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema terastore
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `terastore` DEFAULT CHARACTER SET utf8 ;
USE `terastore` ;

-- -----------------------------------------------------
-- Table `terastore`.`PERMISO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `terastore`.`PERMISO` (
  `ID_permiso` INT NOT NULL AUTO_INCREMENT,
  `Tipo_permiso` VARCHAR(25) NOT NULL,
  `Fecha_creacion_permiso` DATE NOT NULL,
  `Estado_permiso` TINYINT(1) NOT NULL,
  PRIMARY KEY (`ID_permiso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `terastore`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `terastore`.`USUARIO` (
  `ID_usuario` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(255) NOT NULL,
  `Apellido` VARCHAR(255) NOT NULL,
  `Contrasenia` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ID_usuario`),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `terastore`.`CATEGORIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `terastore`.`CATEGORIA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `terastore`.`PRODUCTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `terastore`.`PRODUCTO` (
  `ID_producto` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(255) NOT NULL,
  `Descripcion` VARCHAR(150) NOT NULL,
  `Precio` REAL NOT NULL,
  `Imagen` VARCHAR(255) NOT NULL,
  `Stock` INT(11) NOT NULL,
  `fecha_creacion` TIMESTAMP NOT NULL,
  `CATEGORIA_ID` INT NOT NULL,
  PRIMARY KEY (`ID_producto`),
  INDEX `fk_PRODUCTO_CATEGORIA1_idx` (`CATEGORIA_ID` ASC) VISIBLE,
  UNIQUE INDEX `ID_producto_UNIQUE` (`ID_producto` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUCTO_CATEGORIA1`
    FOREIGN KEY (`CATEGORIA_ID`)
    REFERENCES `terastore`.`CATEGORIA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `terastore`.`MENSAJE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `terastore`.`MENSAJE` (
  `ID_mensaje` INT NOT NULL AUTO_INCREMENT,
  `Contenido` TEXT(255) NOT NULL,
  `Fecha_Envio` DATETIME NOT NULL,
  `USUARIO_ID_usuario` INT NOT NULL,
  `PRODUCTO_ID_producto` INT NOT NULL,
  PRIMARY KEY (`ID_mensaje`),
  UNIQUE INDEX `ID_mensaje_UNIQUE` (`ID_mensaje` ASC) VISIBLE,
  INDEX `fk_MENSAJE_USUARIO1_idx` (`USUARIO_ID_usuario` ASC) VISIBLE,
  INDEX `fk_MENSAJE_PRODUCTO1_idx` (`PRODUCTO_ID_producto` ASC) VISIBLE,
  CONSTRAINT `fk_MENSAJE_USUARIO1`
    FOREIGN KEY (`USUARIO_ID_usuario`)
    REFERENCES `terastore`.`USUARIO` (`ID_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MENSAJE_PRODUCTO1`
    FOREIGN KEY (`PRODUCTO_ID_producto`)
    REFERENCES `terastore`.`PRODUCTO` (`ID_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `terastore`.`PASARELA_PAGO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `terastore`.`PASARELA_PAGO` (
  `ID_pago` INT NOT NULL AUTO_INCREMENT,
  `Metodo_pago` VARCHAR(50) NOT NULL,
  `Fecha_pago` DATETIME NOT NULL,
  PRIMARY KEY (`ID_pago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `terastore`.`PAIS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `terastore`.`PAIS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nombre_pais` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  UNIQUE INDEX `Nombre_UNIQUE` (`Nombre_pais` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `terastore`.`PROVINCIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `terastore`.`PROVINCIA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nombre_provincia` VARCHAR(45) NOT NULL,
  `PAIS_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_PROVINCIA_PAIS1_idx` (`PAIS_ID` ASC) VISIBLE,
  CONSTRAINT `fk_PROVINCIA_PAIS1`
    FOREIGN KEY (`PAIS_ID`)
    REFERENCES `terastore`.`PAIS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `terastore`.`CIUDAD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `terastore`.`CIUDAD` (
  `CP` INT NOT NULL,
  `Nombre_ciudad` VARCHAR(100) NOT NULL,
  `PROVINCIA_ID` INT NOT NULL,
  PRIMARY KEY (`CP`),
  UNIQUE INDEX `CP_UNIQUE` (`CP` ASC) VISIBLE,
  INDEX `fk_CIUDAD_PROVINCIA1_idx` (`PROVINCIA_ID` ASC) VISIBLE,
  CONSTRAINT `fk_CIUDAD_PROVINCIA1`
    FOREIGN KEY (`PROVINCIA_ID`)
    REFERENCES `terastore`.`PROVINCIA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `terastore`.`DIRECCION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `terastore`.`DIRECCION` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nombre_calle` VARCHAR(70) NOT NULL,
  `Numero` INT NOT NULL,
  `CIUDAD_CP` INT NOT NULL,
  `USUARIO_ID_usuario` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_DIRECCION_CIUDAD1_idx` (`CIUDAD_CP` ASC) VISIBLE,
  INDEX `fk_DIRECCION_USUARIO1_idx` (`USUARIO_ID_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_DIRECCION_CIUDAD1`
    FOREIGN KEY (`CIUDAD_CP`)
    REFERENCES `terastore`.`CIUDAD` (`CP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DIRECCION_USUARIO1`
    FOREIGN KEY (`USUARIO_ID_usuario`)
    REFERENCES `terastore`.`USUARIO` (`ID_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `terastore`.`TRANSACCION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `terastore`.`TRANSACCION` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Fecha_creacion_transaccion` TIMESTAMP NOT NULL,
  `Estado_transaccion` VARCHAR(50) NOT NULL,
  `USUARIO_ID_usuario` INT NOT NULL,
  `PASARELA_PAGO_ID_pago` INT NOT NULL,
  `Metodo_envio` VARCHAR(45) NOT NULL,
  `DIRECCION_ID` INT NOT NULL,
  `Subtotal` REAL NOT NULL,
  `Costo_envio` REAL NOT NULL,
  `Total_final` REAL NOT NULL,
  `Codigo_seguimiento` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_TRANSACCIONES_USUARIO1_idx` (`USUARIO_ID_usuario` ASC) VISIBLE,
  INDEX `fk_TRANSACCIONES_PASARELA_PAGO1_idx` (`PASARELA_PAGO_ID_pago` ASC) VISIBLE,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  UNIQUE INDEX `Metodo_envio_UNIQUE` (`Metodo_envio` ASC) VISIBLE,
  INDEX `fk_TRANSACCION_DIRECCION1_idx` (`DIRECCION_ID` ASC) VISIBLE,
  CONSTRAINT `fk_TRANSACCIONES_USUARIO1`
    FOREIGN KEY (`USUARIO_ID_usuario`)
    REFERENCES `terastore`.`USUARIO` (`ID_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TRANSACCIONES_PASARELA_PAGO1`
    FOREIGN KEY (`PASARELA_PAGO_ID_pago`)
    REFERENCES `terastore`.`PASARELA_PAGO` (`ID_pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TRANSACCION_DIRECCION1`
    FOREIGN KEY (`DIRECCION_ID`)
    REFERENCES `terastore`.`DIRECCION` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `terastore`.`PERMISO_USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `terastore`.`PERMISO_USUARIO` (
  `USUARIO_ID_usuario` INT NOT NULL,
  `PERMISO_ID_permiso` INT NOT NULL,
  PRIMARY KEY (`USUARIO_ID_usuario`, `PERMISO_ID_permiso`),
  INDEX `fk_USUARIO_has_PERMISO_PERMISO1_idx` (`PERMISO_ID_permiso` ASC) VISIBLE,
  INDEX `fk_USUARIO_has_PERMISO_USUARIO_idx` (`USUARIO_ID_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_USUARIO_has_PERMISO_USUARIO`
    FOREIGN KEY (`USUARIO_ID_usuario`)
    REFERENCES `terastore`.`USUARIO` (`ID_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USUARIO_has_PERMISO_PERMISO1`
    FOREIGN KEY (`PERMISO_ID_permiso`)
    REFERENCES `terastore`.`PERMISO` (`ID_permiso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `terastore`.`DETALLE_TRANSACCION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `terastore`.`DETALLE_TRANSACCION` (
  `TRANSACCION_ID` INT NOT NULL,
  `PRODUCTO_ID_producto` INT NOT NULL,
  `Cantidad` VARCHAR(45) NOT NULL,
  `Subtotal` REAL NOT NULL,
  PRIMARY KEY (`TRANSACCION_ID`, `PRODUCTO_ID_producto`),
  INDEX `fk_TRANSACCION_has_PRODUCTO_PRODUCTO1_idx` (`PRODUCTO_ID_producto` ASC) VISIBLE,
  INDEX `fk_TRANSACCION_has_PRODUCTO_TRANSACCION1_idx` (`TRANSACCION_ID` ASC) VISIBLE,
  CONSTRAINT `fk_TRANSACCION_has_PRODUCTO_TRANSACCION1`
    FOREIGN KEY (`TRANSACCION_ID`)
    REFERENCES `terastore`.`TRANSACCION` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TRANSACCION_has_PRODUCTO_PRODUCTO1`
    FOREIGN KEY (`PRODUCTO_ID_producto`)
    REFERENCES `terastore`.`PRODUCTO` (`ID_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
